### ISSUE TITLE
db-migrate down Cannot find module error

### ISSUE THREAD

**Issue by weeger** [maherma-adg/db-migrate-plugin-es6cjs#1]
Hi,

Nice work, very helpful, works like a charm with `db-migrate up`, but fails with `db-migrate down`. 

Having error : 

    [ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Cannot find module '/home/site/wwwroot/migrations/20220608082750-my-super-migration'

Thanks !

**Comment by maherma-adg** [comment]
This is a limitation from db-migration. You can update to db-migration@1.0.0-beta.8 and you will don't need this plugin (see [#724](https://github.com/db-migrate/node-db-migrate/pull/724))
